project:
  type: book
  output-dir: ../docs/en

lang: en
bibliography: ../referencias.bib

filters:
  - shinylive

format:
  html:
    embed-resources: false
    self-contained: false
    include-after-body: ../language-switch.html
  pdf:
    documentclass: scrreprt
    keep-tex: true

book:
  title: "Machine Learning and Automatic Classification with R"
  subtitle: "A Practical Approach Using Real Open Data"
  author: "Jesús Gilberto Rodríguez Escobedo"
  date: "2026"
  site-url: "https://gilbertorodriguez59.github.io/libro-machine-learning-r/en/"
  repo-url: "https://github.com/gilbertorodriguez59/libro-machine-learning-r"
  output-file: "Machine-Learning-and-Automatic-Classification-with-R"
  downloads: [pdf]
  navbar:
    right:
      - text: "Español"
        href: ../index.html
  chapters:
    - index.qmd
    - 00-welcome.qmd
    - 00-legal-page.qmd
    - 00-editorial-credits.qmd
    - 00-license-and-academic-use.qmd
    - 00-preface.qmd
    - 00-acknowledgments.qmd
    - 00-google-colab.qmd
    - 01-introduction.qmd
    - 02-data-preparation.qmd
    - 03-exploratory-data-analysis.qmd
    - 04-linear-regression.qmd
    - 05-logistic-regression.qmd
    - 06-knn.qmd
    - 07-decision-trees.qmd
    - 08-random-forest.qmd
    - 09-model-evaluation.qmd
    - 10-svm.qmd
    - 11-naive-bayes.qmd
    - 12-neural-networks.qmd
    - 13-kmeans.qmd
  appendices:
    - glossary.qmd
    - references.qmd
    - figure-index.qmd
    - subject-index.qmd
    - about-the-author.qmd
